services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    links:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - frontend
    restart: always